"""
test_create_resume_prompt.py

This module contains unit tests for the create_resume function from main.py.
It verifies that the generated prompt includes both the job description and
the personal description. Dummy classes are used to simulate the behavior of
the LLM chat object.
"""
import unittest
from main import create_resume

# I used AI to help me write the Dummy class and its functionality.

class DummyResponse:
    """
     A placeholder response class to mimic an LLM response object.
     """
    pass


class DummyChat:
    """
    A dummy chat class that simulates the gemini_chat object.

    The send_message method returns a DummyResponse object with its 'text'
    attribute set to the provided prompt.
    """
    def send_message(self, prompt):
        response = DummyResponse()
        response.text = prompt  # echo the prompt back as the response text
        return response

# tests the create_resume function from main.py
class TestCreateResumePrompt(unittest.TestCase):
    """
    Unit tests for the create_resume function from main.py.

    This class tests whether the prompt generated by create_resume includes
    both the job description and personal description.
    """
    def test_prompt_includes_descriptions(self):
        """
        Test that create_resume's prompt contains both the job description
        and the personal description.
        """
        # define sample descriptions
        job_description = "Mock Job Description"
        personal_description = "Mock Personal Information"
        # create instance of DummyChat to simulate the LLM
        dummy_chat = DummyChat()

        # return the final prompt string
        prompt_result = create_resume(dummy_chat, job_description, personal_description)

        # verify that both pieces of information are present in the prompt
        self.assertIn(job_description, prompt_result, "Job description not found in the prompt.")
        self.assertIn(personal_description,
                      prompt_result, "Personal description not found in the prompt.")


if __name__ == '__main__':
    unittest.main()
